// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using RAMPControl.API.Data;
using System;

namespace RAMPControl.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180430104649_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("RAMPControl.API.Models.DailyWorkComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommentHeading");

                    b.Property<string>("CommentText");

                    b.Property<string>("DateTime");

                    b.HasKey("Id");

                    b.ToTable("DailyComment");
                });
#pragma warning restore 612, 618
        }
    }
}
